GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/62ac62ebb233816d697fd2ba

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "some random chan"
}

###

DELETE http://localhost:3000/subscribers/62ac66429ae416bbe96b8dc2

###

PATCH http://localhost:3000/subscribers/62ac62ebb233816d697fd2ba
Content-Type: application/json

{
    "name": "jhon"
}